### ISSUE TITLE
cluster volumes parameters does not work

### ISSUE THREAD

**Issue by worstkid92** [kurator-dev/kurator#169]
set parametes 
```
    nonRootVolumes:
    - size: 200
      type: gp3
    replicas: 3
    rootVolumeSize:
      size: 100
      type: gp3
```
but the ec2 created are still 8gb

**What you expected to happen**:
create ec2 volumes as parameters set

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kurator version:
- Others:
