### ISSUE TITLE
The `Fleet` request resources has deffierent in crd than in clientSet 

### ISSUE THREAD

**Issue by LiZhenCheng9527** [kurator-dev/kurator#595]
**What happened**:
The `Fleet` has deffierent resources in crd than in clientSet 
```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.8.0
  creationTimestamp: null
  name: fleet.fleet.kurator.dev
spec:
  group: fleet.kurator.dev
  names:
    categories:
    - kurator-dev
    kind: Fleet
    listKind: FleetList
    plural: fleet
    singular: fleet
```
[fleet crd](https://github.com/kurator-dev/kurator/blob/main/manifests/charts/fleet-manager/crds/fleet.kurator.dev_fleet.yaml)
```console
func (c *fleets) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Fleet, err error) {
	result = &v1alpha1.Fleet{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("fleets").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}
```
[fleet clientset](https://github.com/kurator-dev/kurator/blob/main/pkg/client-go/generated/clientset/versioned/typed/fleet/v1alpha1/fleet.go)
**What you expected to happen**:
Both should be the same
**How to reproduce it (as minimally and precisely as possible)**:
Modify the fleet crd

**Environment**:
- Kurator version: 0.6.0
